### ISSUE TITLE
ESGtoolkit package no longer on CRAN

### ISSUE THREAD

**Issue by kummerer94** [Techtonique/esgtoolkit#2]
Hi,

first of all: thank you so much for working on this package and contributing all this work to the community. It is greatly appreciated and this issue is not to be understood as any kind of demand. I just want to understand what is happening.

I have found this repo after the ESGtoolkit package on CRAN has been archived (since the CDvine package has been archived). I could not find any information on why this is the case neither do I know the general process of archiving packages on CRAN. Noticing this, I have googled a bit and found this repository. What I also noticed is that you fixed the problem by using the VineCopula package.

My question is: will this change make it to CRAN eventually? And generally, what is the state of this project? On CRAN I can see that the original package was released in 2014 and then the next update was in August of this year. Are you maintaining this package from now on?

Thank you so much!

Alexander

**Comment by thierrymoudiki** [comment]
Hi,

- "after the ESGtoolkit package on CRAN has been archived": this is a very long story. Very long story of absurd email exchanges (that I kept) and arbitrary decisions. They litterally tried to confiscate it or block the updates, for a reason that's not clear to me.

- "the general process of archiving packages": https://cran.r-project.org/web/packages/policies.html (note that, you can't get your code back, even if you wanted it)

- I'm not "maintaining from now" on (it's already pretty advanced though, no plan to include calibration features, as there are a lot of packages to do just that). I've created it and I've been maintaining it since Adam & Eve. 

Best.

**Comment by kummerer94** [comment]
Hi,

sorry, for some reason I thought you did not create the package. My bad. I should have read more carefully.

Also: Thank you for the quick answer! In some sense, not changing the code of this package in any major way is helpful to us since we depend on the results not changing and are already more than happy with the feature set.

Still very helpful for us to clear this up and quite sorry to hear the problems you had to deal with.

I am closing this for now. Should be good information for anyone else trying to figure out what is happening.

Best
Alexander

**Comment by thierrymoudiki** [comment]
@kummerer94 Would that be too much to ask, if I asked you to email me how you're using it? How am I supposed to not break the API if I don't know how people are using it, and it's just blocked by someone for obscure reasons? 

"for some reason (...)" sounds like a chorus to us. 

Best,

T.

**Comment by kummerer94** [comment]
Sure, I just need some time to go through our code and find the right places. I will send you an email.

Best
Alexander
